--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OutiServer/PMMPTeleporter
build-by-default: true
branches:
- main
projects:
  PMMPTeleporter:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: 4.1.0
      - src: KenCir/PMMPLibFormAPI/LibFormAPI
        version: 1.1.0
...
