<?php

declare(strict_types=1);

namespace outiserver\teleporter;

use Ken_Cir\LibFormAPI\FormStack\StackFormManager;
use outiserver\teleporter\commands\TeleporterCommand;
use outiserver\teleporter\database\teleporter\TeleporterDataManager;
use outiserver\teleporter\language\LanguageManager;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\Config;
use pocketmine\utils\SingletonTrait;
use poggit\libasynql\DataConnector;
use poggit\libasynql\libasynql;
use poggit\libasynql\SqlError;

class Teleporter extends PluginBase
{
    use SingletonTrait;

    public const VERSION = "1.0.0";

    public const CONFIG_VERSION = "1.0.0";

    private DataConnector $dataConnector;

    private TeleporterDataManager $teleporterDataManager;

    private LanguageManager $languageManager;

    private StackFormManager $stackFormManager;

    private Config $config;

    private mixed $databaseConfig;

    protected function onLoad(): void
    {
        self::setInstance($this);
    }

    protected function onEnable(): void
    {
        if (@file_exists("{$this->getDataFolder()}database.yml")) {
            $config = new Config("{$this->getDataFolder()}database.yml", Config::YAML);
            // データベース設定のバージョンが違う場合は
            if ($config->get("version") !== self::VERSION) {
                rename("{$this->getDataFolder()}database.yml", "{$this->getDataFolder()}database.yml.{$config->get("version")}");
                $this->getLogger()->warning("database.yml バージョンが違うため、上書きしました");
                $this->getLogger()->warning("前バージョンのdatabase.ymlは{$this->getDataFolder()}database.yml.{$config->get("version")}にあります");
            }
        }
        if (@file_exists("{$this->getDataFolder()}config.yml")) {
            $config = new Config("{$this->getDataFolder()}config.yml", Config::YAML);
            // データベース設定のバージョンが違う場合は
            if ($config->get("version") !== self::CONFIG_VERSION) {
                rename("{$this->getDataFolder()}config.yml", "{$this->getDataFolder()}config.yml.{$config->get("version")}");
                $this->getLogger()->warning("config.yml バージョンが違うため、上書きしました");
                $this->getLogger()->warning("前バージョンのconfig.ymlは{$this->getDataFolder()}config.yml.{$config->get("version")}にあります");
            }
        }
        $this->saveResource("database.yml");
        $this->saveResource("config.yml");

        $this->config = new Config("{$this->getDataFolder()}config.yml", Config::YAML);
        $this->databaseConfig = (new Config("{$this->getDataFolder()}database.yml", Config::YAML))->get("database");

        $this->dataConnector = libasynql::create($this, $this->databaseConfig, [
            "sqlite" => "sql/sqlite.sql",
            "mysql" => "sql/mysql.sql",
        ]);
        $this->dataConnector->executeGeneric("economy.teleporter.teleporters.init",
            [],
            null,
            function (SqlError $error) {
                $this->getLogger()->error("[SqlError] {$error->getErrorMessage()}");
            });
        $this->dataConnector->waitAll();

        $this->teleporterDataManager = new TeleporterDataManager($this->dataConnector);
        $this->dataConnector->waitAll();

        $this->languageManager = new LanguageManager("{$this->getFile()}resources/lang");

        $this->stackFormManager = new StackFormManager();

        $this->getServer()->getCommandMap()->registerAll($this->getName(),
            [
                new TeleporterCommand($this, "teleporter", "テレポーターコマンド", "/teleporter", [])
            ]);
    }

    /**
     * @return DataConnector
     */
    public function getDataConnector(): DataConnector
    {
        return $this->dataConnector;
    }

    /**
     * @return TeleporterDataManager
     */
    public function getTeleporterDataManager(): TeleporterDataManager
    {
        return $this->teleporterDataManager;
    }

    /**
     * @return StackFormManager
     */
    public function getStackFormManager(): StackFormManager
    {
        return $this->stackFormManager;
    }

    /**
     * @return LanguageManager
     */
    public function getLanguageManager(): LanguageManager
    {
        return $this->languageManager;
    }

    public function getConfig(): Config
    {
        return $this->config; // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getDatabaseConfig(): mixed
    {
        return $this->databaseConfig;
    }
}